apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  labels:
    app: dotnetapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: shriramnat/aspnetapp:ORR3II
          ports:
            - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-svc
spec:
  type: NodePort
  selector:
    app: dotnetapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007