apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  labels:
    app: dotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: aspnetapp:latest
          ports:
            - containerPort: 5000